### ISSUE TITLE
Hidden folders are still found and searched

### ISSUE THREAD

**Issue by jpwilliams** [jpwilliams/microboot#25]
Hidden files are skipped.
Hidden folders should probably be skipped too.

**Comment by jpwilliams** [comment]
Might well be something that needs fixing in [jpwilliams/microloader](https://github.com/jpwilliams/microloader).

**Comment by jacktuck** [comment]
How about respecting .gitignore instead / too? Perhaps a .microboot too?

**Comment by jpwilliams** [comment]
😲 That's a cool idea.
Might prefer an option on that though; it taking on config automatically's a bit scary.

Currently those files I wish to keep but not load I'll prefix with a `.` so they don't load and wanted to be able to do the same with folders.

I like the `.gitignore` thing though. `--useGitIgnore`? 😀

**Comment by jpwilliams** [comment]
Released in `2.1.4`.
